// -----------------------------------------------------------------------------
// Automatically generated by 'functions_config.rb'
// DO NOT MANUALLY EDIT THIS FILE!
// -----------------------------------------------------------------------------

#include <\x\alive\addons\sys_logistics\script_component.hpp>

#define TESTS ["logistics"]

SCRIPT(test);

// ----------------------------------------------------------------------------

LOG("=== Testing sys_logistics ===");

{
	call compile preprocessFileLineNumbers format ["\x\alive\addons\sys_logistics\tests\test_%1.sqf", _x];
} forEach TESTS;

nil;
