// Generated by preset_tool.py from the .preset files beside this config.
// Do not edit by hand: a preset is the source of truth and this is written
// from it, so an edit here is lost the next time a preset is accepted.

class CfgEditorCategories {
    class ALiVE_PresetCat {
        displayName = "ALiVE Presets";
    };
};

class CfgEditorSubcategories {
    class ALiVE_PresetSub {
        displayName = "Scenario presets";
    };
};

class Cfg3DEN {
    class Compositions {
        class ALiVE_Preset_nato_occupies_stratis {
            path = "x\alive\addons\sys_presets\compositions\nato_occupies_stratis";
            side = 1;
            editorCategory = "ALiVE_PresetCat";
            editorSubcategory = "ALiVE_PresetSub";
            displayName = "NATO takes and holds an island";
            icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
            useSideColorOnIcon = 1;
        };
    };
};
