// Generated by preset_tool.py. Included INSIDE class CfgALiVEPresets, so
// the shipped presets and the never-shared list stay one class: two
// declarations of the same class at the root will not rapify.
class Shipped {
    class nato_holds_one_area {
        name = "NATO holds one area of the island";
        description = "A NATO commander that fights inside one TAOR marker instead of across the whole island. The marker is part of the preset, so it arrives where you drop the preset and at the size it was saved with. Drag it or resize it before you start and the commander takes its objectives from the new boundary.";
        text = "[""ALIVEPRESET"",2,[""NATO holds one area of the island"",""A NATO commander that fights inside one TAOR marker instead of across the whole island. The marker is part of the preset, so it arrives where you drop the preset and at the size it was saved with. Drag it or resize it before you start and the commander takes its objectives from the new boundary."",""ALiVE"",""Stratis"",""3.2.0.2604133"",""2026-09-21""],[[""ALiVE_require"",[]],[""ALiVE_sys_profile"",[]],[""ALiVE_mil_OPCOM"",[[""ALiVE_mil_opcom_customName"",""NATO""],[""ALiVE_mil_opcom_controltype"",""occupation""],[""ALiVE_mil_opcom_factions"",""[""""BLU_F""""]""]]],[""ALiVE_mil_placement"",[[""ALiVE_mil_placement_taor"",""BLUFOR_TAOR""]]]],[[2,3]],[],[],[[""BLUFOR_TAOR"","""",0,[0,0],[2509,1679],0,""Solid"",""ColorWEST"",0.77,""""]]]";
    };
    class nato_occupies_stratis {
        name = "NATO takes and holds an island";
        description = "A NATO commander that takes and holds the whole island, its forces spread across the military objectives the map index turns up. Somewhere to start from: drop in your own playable units, or swap NATO for a faction that suits a different map.";
        text = "[""ALIVEPRESET"",1,[""NATO takes and holds an island"",""A NATO commander that takes and holds the whole island, its forces spread across the military objectives the map index turns up. Somewhere to start from: drop in your own playable units, or swap NATO for a faction that suits a different map."",""ALiVE"",""Stratis"",""3.2.0.2604133"",""2026-09-20""],[[""ALiVE_require"",[]],[""ALiVE_sys_profile"",[]],[""ALiVE_mil_OPCOM"",[[""ALiVE_mil_opcom_customName"",""NATO""],[""ALiVE_mil_opcom_controltype"",""occupation""],[""ALiVE_mil_opcom_factions"",""[""""BLU_F""""]""]]],[""ALiVE_mil_placement"",[]]],[[2,3]],[],[]]";
    };
};
