#include "\x\alive\addons\mil_C2ISTAR\script_component.hpp"
SCRIPT(taskSelectAutoGeneratedType);

/* ----------------------------------------------------------------------------
Function: ALIVE_fnc_taskSelectAutoGeneratedType

Description:
Select an autogenerated task type, collapsing Hearts and Minds tasking down to
one phase-appropriate option for the nearest eligible civilian cluster.

Parameters:

Returns:
String

Examples:
(begin example)
private _taskType = [ALIVE_autoGeneratedTasks, position player, "Short", "WEST", "BLU_F", []] call ALIVE_fnc_taskSelectAutoGeneratedType;
(end)

See Also:

Author:
OpenAI
---------------------------------------------------------------------------- */

params [
    ["_taskPool", [], [[]]],
    ["_taskLocation", [], [[]]],
    ["_taskLocationType", "Short", [""]],
    ["_taskSide", ""],
    ["_taskFaction", "", [""]],
    ["_tasksCurrent", [], [[]]]
];

if (_taskPool isEqualTo []) exitWith {""};

private _heartsAndMindsTasks = [
    "AidDelivery",
    "SupplyConvoy",
    "MeetLocalLeader",
    "VIPEscort",
    "SecureCommunityEvent",
    "RepairCriticalService"
];
private _candidatePool = +_taskPool;
private _availableHeartsAndMindsTasks = _candidatePool select {_x in _heartsAndMindsTasks};

if (_taskLocation isEqualTo []) exitWith {selectRandom _candidatePool};

private _heartsAndMindsWeight = count _availableHeartsAndMindsTasks;
_candidatePool = _candidatePool - _heartsAndMindsTasks;

if (_heartsAndMindsWeight > 0) then {
    private _clusterData = [_taskLocation, _taskLocationType, _taskSide, -100000, 100000, _taskFaction, _tasksCurrent, false] call ALIVE_fnc_taskGetCivilianCluster;

    if !(_clusterData isEqualTo []) then {
        private _supportState = [_clusterData, 2, []] call BIS_fnc_param;
        private _phase = "Stabilize";
        private _selectionGroups = [
            ["SupplyConvoy", "AidDelivery"],
            ["VIPEscort", "MeetLocalLeader"],
            ["RepairCriticalService", "SecureCommunityEvent"]
        ];

        if !(_supportState isEqualTo []) then {
            _phase = [_supportState, "phase", "Stabilize"] call ALIVE_fnc_hashGet;
        };

        _selectionGroups = switch (_phase) do {
            case "Consolidate": {
                [
                    ["SecureCommunityEvent", "RepairCriticalService"],
                    ["VIPEscort", "MeetLocalLeader"],
                    ["AidDelivery", "SupplyConvoy"]
                ]
            };
            case "Build": {
                [
                    ["RepairCriticalService", "SecureCommunityEvent"],
                    ["VIPEscort", "MeetLocalLeader"],
                    ["SupplyConvoy", "AidDelivery"]
                ]
            };
            case "Engage": {
                [
                    ["VIPEscort", "MeetLocalLeader"],
                    ["SupplyConvoy", "AidDelivery"],
                    ["RepairCriticalService", "SecureCommunityEvent"]
                ]
            };
            default {
                [
                    ["SupplyConvoy", "AidDelivery"],
                    ["VIPEscort", "MeetLocalLeader"],
                    ["RepairCriticalService", "SecureCommunityEvent"]
                ]
            };
        };

        private _selectedTaskType = "";

        {
            private _availableGroup = _x select {_x in _availableHeartsAndMindsTasks};
            if !(_availableGroup isEqualTo []) exitWith {
                _selectedTaskType = selectRandom _availableGroup;
            };
        } forEach _selectionGroups;

        if !(_selectedTaskType isEqualTo "") then {
            for "_i" from 1 to _heartsAndMindsWeight do {
                _candidatePool pushBack _selectedTaskType;
            };
        };
    };
};

if (_candidatePool isEqualTo []) exitWith {""};

selectRandom _candidatePool
