#include "\x\alive\addons\mil_C2ISTAR\script_component.hpp"
SCRIPT(taskSelectAutoGeneratedType);

/* ----------------------------------------------------------------------------
Function: ALIVE_fnc_taskSelectAutoGeneratedType

Description:
Select an autogenerated task type, collapsing Hearts and Minds tasking down to
one phase-appropriate option for the nearest eligible civilian cluster.

Parameters:
Array - Task pool
Array - Task location
String - Task location type
String|Side - Task side
String - Task faction
Array - Current tasks

Returns:
String

Author:
OpenAI
---------------------------------------------------------------------------- */

params [
    ["_taskPool", [], [[]]],
    ["_taskLocation", [], [[]]],
    ["_taskLocationType", "Short", [""]],
    ["_taskSide", ""],
    ["_taskFaction", "", [""]],
    ["_tasksCurrent", [], [[]]]
];

if (_taskPool isEqualTo []) exitWith {""};

private _allHeartsAndMindsTasks = [
    "AidDelivery",
    "SupplyConvoy",
    "MeetLocalLeader",
    "VIPEscort",
    "SecureCommunityEvent",
    "RepairCriticalService",
    "MedicalOutreach",
    "CheckpointPartnership",
    "InformantExfiltration",
    "MarketReopening"
];
private _legacyHeartsAndMindsTasks = [
    "AidDelivery",
    "SupplyConvoy",
    "MeetLocalLeader",
    "VIPEscort",
    "SecureCommunityEvent",
    "RepairCriticalService"
];
private _candidatePool = +_taskPool;
private _availableHeartsAndMindsTasks = _candidatePool select {_x in _allHeartsAndMindsTasks};
private _civicStateEnabled = missionNamespace getVariable ["ALIVE_civicStateEnabled", false];
private _enabledTasks = missionNamespace getVariable ["ALIVE_civicEnabledTaskFamilies", _allHeartsAndMindsTasks apply {toUpper _x}];
private _taskWeights = missionNamespace getVariable ["ALIVE_civicTaskWeights", [] call ALIVE_fnc_hashCreate];
private _duplicatePenalty = (missionNamespace getVariable ["ALIVE_civicDuplicateTaskPenalty", 0.15]) max 0;

if (!_civicStateEnabled) then {
    _availableHeartsAndMindsTasks = _availableHeartsAndMindsTasks select {_x in _legacyHeartsAndMindsTasks};
};

_availableHeartsAndMindsTasks = _availableHeartsAndMindsTasks select {
    (toUpper _x) in _enabledTasks &&
    {([_taskWeights, toUpper _x, 1] call ALIVE_fnc_hashGet) > 0}
};

if (_taskLocation isEqualTo []) exitWith {
    private _fallbackPool = if (_availableHeartsAndMindsTasks isEqualTo []) then {_candidatePool} else {(_candidatePool - _allHeartsAndMindsTasks) + _availableHeartsAndMindsTasks};
    selectRandom _fallbackPool
};

private _heartsAndMindsWeight = count _availableHeartsAndMindsTasks;
_candidatePool = _candidatePool - _allHeartsAndMindsTasks;

if (_heartsAndMindsWeight > 0) then {
    private _clusterData = [_taskLocation, _taskLocationType, _taskSide, -100000, 100000, _taskFaction, _tasksCurrent, false] call ALIVE_fnc_taskGetCivilianCluster;

    if !(_clusterData isEqualTo []) then {
        private _supportState = [_clusterData, 2, []] call BIS_fnc_param;
        private _selectedTaskType = "";

        if (_civicStateEnabled && {!(_supportState isEqualTo [])}) then {
            private _statusBand = [_supportState, "statusBand", "Hostile"] call ALIVE_fnc_hashGet;
            private _weakestAxis = [_supportState, "weakestAxis", "trust"] call ALIVE_fnc_hashGet;
            private _lastTaskType = [_supportState, "lastTaskType", ""] call ALIVE_fnc_hashGet;
            private _repeatStreak = ([_supportState, "successStreak", 0] call ALIVE_fnc_hashGet) max ([_supportState, "failureStreak", 0] call ALIVE_fnc_hashGet);
            private _retaliationAxis = [_supportState, "lastRetaliationAxis", ""] call ALIVE_fnc_hashGet;
            private _weightedTasks = [];

            {
                private _taskType = _x;
                private _profile = [_taskType] call ALIVE_fnc_taskGetCivicTaskProfile;
                private _weight = [_taskWeights, toUpper _taskType, 1] call ALIVE_fnc_hashGet;
                private _score = _weight max 0;
                private _primaryAxis = [_profile, "primaryAxis", "trust"] call ALIVE_fnc_hashGet;
                private _secondaryAxis = [_profile, "secondaryAxis", "security"] call ALIVE_fnc_hashGet;
                private _preferredStatusBands = [_profile, "preferredStatusBands", []] call ALIVE_fnc_hashGet;

                if (_score > 0) then {
                    if (_primaryAxis == _weakestAxis) then {
                        _score = _score * 5;
                    } else {
                        if (_secondaryAxis == _weakestAxis) then {
                            _score = _score * 2.5;
                        } else {
                            _score = _score * 0.8;
                        };
                    };

                    if (_statusBand in _preferredStatusBands) then {
                        _score = _score * 2;
                    } else {
                        _score = _score * 0.85;
                    };

                    if (_retaliationAxis != "" && {(_primaryAxis == _retaliationAxis) || (_secondaryAxis == _retaliationAxis)}) then {
                        _score = _score * 1.5;
                    };

                    if (_lastTaskType == _taskType) then {
                        _score = _score * ((1 - (_duplicatePenalty * (_repeatStreak min 4))) max 0.25);
                    };

                    for "_i" from 1 to ((ceil _score) min 12) do {
                        _weightedTasks pushBack _taskType;
                    };
                };
            } forEach _availableHeartsAndMindsTasks;

            if !(_weightedTasks isEqualTo []) then {
                _selectedTaskType = selectRandom _weightedTasks;
            };
        } else {
            private _phase = "Stabilize";
            private _selectionGroups = [
                ["SupplyConvoy", "AidDelivery"],
                ["VIPEscort", "MeetLocalLeader"],
                ["RepairCriticalService", "SecureCommunityEvent"]
            ];

            if !(_supportState isEqualTo []) then {
                _phase = [_supportState, "phase", "Stabilize"] call ALIVE_fnc_hashGet;
            };

            _selectionGroups = switch (_phase) do {
                case "Consolidate": {
                    [
                        ["SecureCommunityEvent", "RepairCriticalService"],
                        ["VIPEscort", "MeetLocalLeader"],
                        ["AidDelivery", "SupplyConvoy"]
                    ]
                };
                case "Build": {
                    [
                        ["RepairCriticalService", "SecureCommunityEvent"],
                        ["VIPEscort", "MeetLocalLeader"],
                        ["SupplyConvoy", "AidDelivery"]
                    ]
                };
                case "Engage": {
                    [
                        ["VIPEscort", "MeetLocalLeader"],
                        ["SupplyConvoy", "AidDelivery"],
                        ["RepairCriticalService", "SecureCommunityEvent"]
                    ]
                };
                default {
                    [
                        ["SupplyConvoy", "AidDelivery"],
                        ["VIPEscort", "MeetLocalLeader"],
                        ["RepairCriticalService", "SecureCommunityEvent"]
                    ]
                };
            };

            {
                private _availableGroup = _x select {_x in _availableHeartsAndMindsTasks};
                if !(_availableGroup isEqualTo []) exitWith {
                    _selectedTaskType = selectRandom _availableGroup;
                };
            } forEach _selectionGroups;
        };

        if !(_selectedTaskType isEqualTo "") then {
            for "_i" from 1 to _heartsAndMindsWeight do {
                _candidatePool pushBack _selectedTaskType;
            };
        };
    };
};

if (_candidatePool isEqualTo []) exitWith {""};
selectRandom _candidatePool
