#include <\x\alive\addons\mil_C2ISTAR\script_component.hpp>
SCRIPT(taskDisable);

/* ----------------------------------------------------------------------------
Function: ALiVE_fnc_taskDisable

Description:
Disables selected task types (generic or autogenerated).
Intended to be put in init.sqf of a mission like ["generated","autogenerated"] call ALiVE_fnc_TaskDisable;

Parameters:
Array - Pass one or both strings ["generated","autogenerated"] 

Returns:
nothing

Attributes:


Examples:
(begin example)
// put in init.sqf
["generated"] call ALiVE_fnc_taskDisable;
(end)

See Also:

Author:
Highhead

Peer reviewed:
nil
---------------------------------------------------------------------------- */

private _params = _this;
private _timeOut = time;

{
	switch _x do {
	    case "generated" : {
            waituntil {!isnil "ALIVE_generatedTasks" || {time - _timeout > 600}};
            
            ALIVE_generatedTasks = [] call ALiVE_fnc_HashCreate;
        };
        case "autogenerated" : {
            waituntil {!isnil "ALIVE_autoGeneratedTasks" || {time - _timeout > 600}};
            
            ALIVE_autoGeneratedTasks = [];
        };
	};
} foreach _params;