class CfgHints
{
	class PREFIX
	{
		// Topic title (displayed only in topic listbox in Field Manual)
		displayName = "ALiVE Mod";
		class ADDON
		{
			// Hint title, filled by arguments from 'arguments' param
			displayName = "ALiVE Missions";
            // Optional hint subtitle, filled by arguments from 'arguments' param
			displayNameShort = "How to Play ALiVE";
			// Structured text, filled by arguments from 'arguments' param
			description = "Scenarios built with ALiVE can be played just like any other mission.  However, unlike in other missions, AI forces actively engage in the struggle for tactical supremacy of the battlefield, either against or alongside player forces.  The %3Military AI Commanders (OPCOM)%4 will identify, recce and attempt to seize strategic objectives.  They will use their forces to occupy towns, industrial complexes and military establishments, sending out clearance patrols to protect the area whilst they reorg.  They will request replacement vehicles and units as they take battle casualties, which are transported to the front line from logistics depots behind the lines.%1%1Here are some hints to get you started playing an ALiVE scenario.%1%1%2The %3ALiVE Action Menu%4 is access by pressing the %3Right App Key%4 or %3Custom Key 22%4 in the ArmA3 Options.%1%2If you are unsure what to do, request an autogenerated %3Player Tasks%4 from OPCOM.%1%2%3Military Intel%4 will briefly flash up on the map where enemy activity has been detected.  Tactical Intel decays rapidly so quick action is needed.%1%2Use %3Combat Support%4 to transport players quickly to a safe Helicopter Landing Site near the action.%1%2Request reinforcements and equipment from %3Player Resupply%4.%1%2Try to interdict enemy convoys to prevent them supplying front line troops.  This will rapidly halt OPCOM’s advance.%1%2If the worst happens, use one of the %3Multispawn%4 options to get back into the action quickly.%1%2With %3ALiVE Data%4 enabled, you can review your progress on the %3ALiVEmod.com War Room%4 and compare stats with other players and groups.";
            // Optional structured text, filled by arguments from 'arguments' param (first argument is %11, see notes bellow), grey color of text
            tip = "Request an autogenerated task from the AI Commander if you are unsure what to do next.";
			arguments[] = {
				{{"getOver"}},  // Double nested array means assigned key (will be specially formatted)
                {"name"},       // Nested array means element (specially formatted part of text)
				"name player"   // Simple string will be simply compiled and called
                                // String is used as a link to localization database in case it starts by str_
			};
			// Optional image
			image = "x\alive\addons\ui\logo_alive_square.paa";
			// optional parameter for not showing of image in context hint in mission (default false))
			noImage = false;
		};
	};
};

/*

    First item from arguments field in config is inserted in text via variable %11, second item via %12, etc.
    Variables %1 - %10 are hardcoded:
         %1 - small empty line
         %2 - bullet (for item in list)
         %3 - highlight start
         %4 - highlight end
         %5 - warning color formated for using in structured text tag
         %6 - BLUFOR color attribute
         %7 - OPFOR color attribute
         %8 - Independent color attribute
         %9 - Civilian color attribute
         %10 - Unknown side color attribute
    color formated for using in structured text is string: "color = 'given_color'"
*/

