#include "\x\alive\addons\main\script_component.hpp"
SCRIPT(resolveTaskTypeChoice);
/* ----------------------------------------------------------------------------
Function: ALIVE_fnc_resolveTaskTypeChoice

Description:
Module-init resolver for the ALiVE_TaskTypeChoice family. Parses the
canonical flat comma-separated string saved by the attribute and
applies it to the target global registry (e.g. ALIVE_autoGeneratedTasks)
either by REPLACE (full overwrite) or APPEND (union with existing
contents, deduped).

Two merge modes:
    "REPLACE" (default) - target registry is fully replaced with the
                          user-supplied list. Matches the legacy
                          init.sqf override pattern (mission-makers
                          assign ALIVE_autoGeneratedTasks = [...] in
                          init.sqf which simply overwrites).
    "APPEND"            - existing entries are kept and the user-
                          supplied list is added on top, deduped.
                          Useful when extending defaults with mod-
                          provided task types without losing the
                          stock list.

Empty value = no-op (registry unchanged regardless of mode).

Parameters:
    [_value, _registryName, _mode]
    _value          : STRING - canonical Task1,Task2,Task3 string
    _registryName   : STRING - global variable name to write to
                      (e.g. "ALIVE_autoGeneratedTasks")
    _mode           : STRING - "REPLACE" or "APPEND" (default REPLACE)

Returns:
    SCALAR - count of entries written to the registry (0 if no-op).

Examples:
(begin example)
private _value = _logic getVariable ["customAutoGeneratedTasks", ""];
[_value, "ALIVE_autoGeneratedTasks", "REPLACE"] call ALIVE_fnc_resolveTaskTypeChoice;
(end)

Author:
Jman
---------------------------------------------------------------------------- */

params [
    ["_value", "", [""]],
    ["_registryName", "", [""]],
    ["_mode", "REPLACE", [""]]
];

if (_value == "") exitWith { 0 };
if (_registryName == "") exitWith {
    diag_log "ALIVE resolveTaskTypeChoice: empty registry name";
    0
};

_mode = toUpper _mode;
if !(_mode in ["REPLACE", "APPEND"]) then {
    diag_log format ["ALIVE resolveTaskTypeChoice: unknown mode '%1', defaulting to REPLACE", _mode];
    _mode = "REPLACE";
};

private _parsed = [];
{
    private _t = _x;
    while {count _t > 0 && {(_t select [0, 1]) == " "}} do { _t = _t select [1] };
    while {count _t > 0 && {(_t select [count _t - 1, 1]) == " "}} do { _t = _t select [0, count _t - 1] };
    if (_t != "") then { _parsed pushBackUnique _t };
} forEach ([_value, ","] call CBA_fnc_split);

if (count _parsed == 0) exitWith { 0 };

if (_mode == "APPEND") then {
    private _existing = missionNamespace getVariable [_registryName, []];
    if (typeName _existing != "ARRAY") then { _existing = []; };
    {
        if !(_x in _existing) then { _existing pushBack _x; };
    } forEach _parsed;
    missionNamespace setVariable [_registryName, _existing];
    count _existing
} else {
    missionNamespace setVariable [_registryName, _parsed];
    count _parsed
};
