#include "\x\alive\addons\main\script_component.hpp"
SCRIPT(edenTaskTypeChoiceLoad);
/* ----------------------------------------------------------------------------
Function: ALIVE_fnc_edenTaskTypeChoiceLoad

Description:
Eden-attribute `attributeLoad` handler for the ALiVE_TaskTypeChoice
family. Populates the multi-select listbox (IDC 100) with the
available task-type names for the registry the variant control points
at (e.g. ALIVE_autoGeneratedTasks for the _AutoGenerated variant),
ticks rows that match the saved value, and pre-fills the override
Edit (IDC 102) with anything saved that the listbox doesn't surface.

Storage format on the logic / SQM:
    Task1,Task2,Task3
Flat comma-separated string (no faction keying - tasks are global,
not per-faction). Empty value = no override (the resolver leaves the
target registry unchanged at runtime).

Flow:
1. Lazy-load Tasks.hpp if the target registry is nil (3DEN editor
   context where staticDataHandler hasn't run)
2. Resolve stored value (priority: SQM `_value` > logic var > "")
3. Parse stored value into a deduped list
4. Populate listbox from registry contents
5. Tick rows that match parsed entries
6. Anything in the parsed value not surfaced in the listbox goes
   into the override Edit (so unrecognised mod tasks are preserved)

Parameters:
    [_display, _kindToken, _varName, _titleStr, _sqmValue]
    _display    : DISPLAY - Eden attribute display
    _kindToken  : STRING - identifies the target registry
                  ("autoGenerated" -> ALIVE_autoGeneratedTasks)
    _varName    : STRING - logic-variable name (e.g.
                  "customAutoGeneratedTasks")
    _titleStr   : STRING - localised title text or $STR_ key
    _sqmValue   : STRING - SQM-deserialised value (Cfg3DEN's `_value`)

Author:
Jman
---------------------------------------------------------------------------- */

private _display = controlNull;
private _kindToken = "autoGenerated";
private _varName = "customAutoGeneratedTasks";
private _titleStr = "Override:";
private _sqmValue = "";

if (typeName _this == "ARRAY") then {
    if (count _this > 0) then { _display = _this select 0; };
    if (count _this > 1 && {typeName (_this select 1) == "STRING"}) then { _kindToken = _this select 1; };
    if (count _this > 2 && {typeName (_this select 2) == "STRING"}) then { _varName = _this select 2; };
    if (count _this > 3 && {typeName (_this select 3) == "STRING"}) then { _titleStr = _this select 3; };
    if (count _this > 4 && {typeName (_this select 4) == "STRING"}) then { _sqmValue = _this select 4; };
} else {
    _display = _this;
};

if (isNull _display) exitWith {
    ["ALIVE TaskTypeChoice LOAD: null display"] call ALiVE_fnc_dump;
};

// ------------------------------------------------------------------------
// Title text. Resolves $STR_ keys via localize.
// ------------------------------------------------------------------------
private _titleResolved = _titleStr;
if (count _titleStr > 0 && {(_titleStr select [0, 1]) == "$"}) then {
    _titleResolved = localize (_titleStr select [1]);
};
private _titleCtrl = _display controlsGroupCtrl 101;
if (!isNull _titleCtrl) then { _titleCtrl ctrlSetText _titleResolved; };

// ------------------------------------------------------------------------
// Map kind token to global registry variable name.
//   autoGenerated -> ALIVE_autoGeneratedTasks (all task types)
//   civic         -> "" (no global registry; populated from the closed
//                   _hmTasks list of Hearts-and-Minds task families
//                   defined below)
// ------------------------------------------------------------------------
private _registryName = switch (_kindToken) do {
    case "autoGenerated": { "ALIVE_autoGeneratedTasks" };
    case "civic":         { "" };
    default               { "" };
};

// ------------------------------------------------------------------------
// Lazy-load Tasks.hpp if the target registry is nil. Same trick as
// fnc_listFactionVehicleClasses uses for the static-data registries -
// 3DEN editor context doesn't run staticDataHandler, so the global is
// undefined until we force-compile the .hpp here. Aliases the ALiVE
// hash wrappers (Tasks.hpp uses createHashMap-style flat assignments,
// no hash calls, so technically not needed, but defensive).
// ------------------------------------------------------------------------
if (_registryName != "" && {isNil _registryName}) then {
    ["ALIVE TaskTypeChoice LOAD: registry %1 not loaded - lazy-loading Tasks.hpp", _registryName] call ALiVE_fnc_dump;
    if (isNil "ALIVE_fnc_hashCreate") then { ALIVE_fnc_hashCreate = CBA_fnc_hashCreate; };
    if (isNil "ALIVE_fnc_hashSet")    then { ALIVE_fnc_hashSet    = CBA_fnc_hashSet; };
    if (isNil "ALIVE_fnc_hashGet")    then { ALIVE_fnc_hashGet    = CBA_fnc_hashGet; };
    call compile preprocessFileLineNumbers "\x\alive\addons\main\static\Tasks.hpp";
};

private _registryClasses = if (_registryName != "") then { missionNamespace getVariable [_registryName, []] } else { [] };
if (typeName _registryClasses != "ARRAY") then { _registryClasses = []; };

// ------------------------------------------------------------------------
// Stored-value resolution.
// ------------------------------------------------------------------------
private _selected = get3DENSelected "logic";
private _logicObj = if (count _selected > 0) then { _selected select 0 } else { objNull };

private _storedFromLogic = if (!isNull _logicObj) then {
    _logicObj getVariable [_varName, nil]
} else {
    nil
};
private _edenValue = _display getVariable "value";

private _value = "";
if (!isNil "_edenValue" && {typeName _edenValue == "STRING"} && {_edenValue != ""}) then {
    _value = _edenValue;
};
if (!isNil "_storedFromLogic" && {typeName _storedFromLogic == "STRING"} && {_storedFromLogic != ""}) then {
    _value = _storedFromLogic;
};
if (_sqmValue != "") then {
    _value = _sqmValue;
};

// ------------------------------------------------------------------------
// Parse stored value into deduped list.
// ------------------------------------------------------------------------
private _selectedTasks = [];
if (_value != "") then {
    {
        private _t = _x;
        while {count _t > 0 && {(_t select [0, 1]) == " "}} do { _t = _t select [1] };
        while {count _t > 0 && {(_t select [count _t - 1, 1]) == " "}} do { _t = _t select [0, count _t - 1] };
        if (_t != "") then { _selectedTasks pushBackUnique _t };
    } forEach ([_value, ","] call CBA_fnc_split);
};

// ------------------------------------------------------------------------
// Populate listbox from the registry. Sort alphabetically so the order
// is stable across re-opens regardless of how Tasks.hpp orders entries.
// ------------------------------------------------------------------------
private _ctrl = _display controlsGroupCtrl 100;
if (isNull _ctrl) exitWith {
    ["ALIVE TaskTypeChoice LOAD: listbox control (IDC 100) not found"] call ALiVE_fnc_dump;
};
lbClear _ctrl;

// Hearts-and-Minds (civic-state) task types - kept in sync with the
// _allCivicTasks list in addons/mil_c2istar/fnc_C2ISTAR.sqf (the
// canonical source). Visually decorated with an "[H&M]" suffix so
// mission-makers can spot them at a glance; lbData stays the bare
// task name so the save handler is unaffected.
private _hmTasks = ["AidDelivery", "SupplyConvoy", "MeetLocalLeader", "VIPEscort", "SecureCommunityEvent", "RepairCriticalService", "MedicalOutreach", "CheckpointPartnership", "InformantExfiltration", "MarketReopening"];

// Friendly-title lookup. ALIVE_generatedTasks is populated by Tasks.hpp
// (the same lazy-load that gave us ALIVE_autoGeneratedTasks above);
// each entry maps a task type name to [friendlyTitle, options]. Use
// the friendly title as the primary listbox text + bracket the raw
// task name so mission-makers can still see what they'd type in
// init.sqf to match (and so acronyms like OCA / CSAR don't surface
// without their full names).
private _friendlyOf = {
    params ["_taskName"];
    if (isNil "ALIVE_generatedTasks") exitWith { _taskName };
    private _meta = [ALIVE_generatedTasks, _taskName] call CBA_fnc_hashGet;
    if (typeName _meta != "ARRAY" || {count _meta == 0}) exitWith { _taskName };
    private _title = _meta select 0;
    if (typeName _title != "STRING" || {_title == ""}) exitWith { _taskName };
    _title
};

// Source list: which task names to surface in the listbox. The
// autoGenerated variant draws from the global registry; the civic
// variant draws from the closed H&M task list directly (no registry
// dependency since every civic task is by definition in _hmTasks).
private _sourceList = switch (_kindToken) do {
    case "autoGenerated": { _registryClasses };
    case "civic":         { _hmTasks };
    default               { _registryClasses };
};

// Civic-only filter: when the C2ISTAR module's civicStateEnabled
// attribute is OFF, the runtime picker (fnc_taskSelectAutoGeneratedType)
// restricts H&M generation to the legacy 6 families. The other 4 are
// silently dropped even if ticked. Hide them from BOTH listboxes
// (autoGenerated + civic) so the configuration UI matches what will
// actually spawn. Mission-maker re-opens the attribute panel after
// toggling civicStateEnabled to see the refreshed listbox (Eden
// doesn't auto-refresh listboxes on sibling Combo changes within
// the same panel session).
//
// civicStateEnabled is placed BEFORE customAutoGeneratedTasks in
// the CfgVehicles attribute order so it's visible / decided first
// (see mil_c2istar/CfgVehicles.hpp).
private _civicOnlyTasks = ["MedicalOutreach", "CheckpointPartnership", "InformantExfiltration", "MarketReopening"];
private _civicStateEnabled = false;
private _selectedLogics = get3DENSelected "logic";
if (count _selectedLogics > 0) then {
    private _logicObj = _selectedLogics select 0;
    if (!isNull _logicObj) then {
        // Eden stores Combo values as strings via the attribute
        // expression - coerce defensively. Default false matches the
        // CfgVehicles default; first-time configuration sees a
        // legacy-6-only listbox.
        private _val = _logicObj getVariable ["civicStateEnabled", false];
        _civicStateEnabled = switch (typeName _val) do {
            case "BOOL":   { _val };
            case "STRING": { (toLower _val) == "true" };
            default        { false };
        };
    };
};

if (!_civicStateEnabled) then {
    _sourceList = _sourceList - _civicOnlyTasks;
};

// Insurgency filter: InsurgencyDestroyAssets / InsurgencyPatrol
// require an Asymmetric-mode mil_opcom module in the scene
// (fnc_taskGetInsurgencyLocation.sqf:50 hard-filters
// `_controlType == "asymmetric"`). Without one, these tasks silently
// can't generate. Walk all3DENEntities looking for any OPCOM with
// controltype="asymmetric"; if none, hide the two insurgency tasks
// from the listbox + override field. Uses the same all3DENEntities
// walk idiom as fnc_edenValidateOpcomFactions.
//
// Only relevant for the autoGenerated picker (civic listbox draws
// from _hmTasks which doesn't include the insurgency tasks anyway,
// so the subtraction is a no-op for that kind).
private _insurgencyTasks = ["InsurgencyDestroyAssets", "InsurgencyPatrol"];
private _hasAsymmetricOpcom = false;
{
    {
        if (_x isEqualType objNull && {!isNull _x} && {(typeOf _x) == "ALiVE_mil_OPCOM"}) then {
            private _ct = _x getVariable ["controltype", ""];
            if (typeName _ct == "STRING" && {(toLower _ct) == "asymmetric"}) exitWith {
                _hasAsymmetricOpcom = true;
            };
        };
    } forEach _x;
    if (_hasAsymmetricOpcom) exitWith {};
} forEach all3DENEntities;

if (!_hasAsymmetricOpcom) then {
    _sourceList = _sourceList - _insurgencyTasks;
};

// H&M suffix decoration is informative for the autoGenerated picker
// (where mission-makers see a mix of H&M and non-H&M tasks). For the
// civic picker every row is H&M so the suffix is noise; suppress it.
private _showHmSuffix = (_kindToken != "civic");

private _surfacedSet = createHashMap;
private _sortedSource = +_sourceList;
_sortedSource sort true;
{
    private _task = _x;
    if (typeName _task == "STRING" && {_task != ""}) then {
        private _friendly = [_task] call _friendlyOf;
        private _label = if (_friendly != _task) then { format ["%1 (%2)", _friendly, _task] } else { _task };
        if (_showHmSuffix && {_task in _hmTasks}) then { _label = format ["%1  [H&M]", _label]; };
        private _idx = _ctrl lbAdd _label;
        _ctrl lbSetData [_idx, _task];
        _surfacedSet set [_task, _idx];
    };
} forEach _sortedSource;

// ------------------------------------------------------------------------
// Tick saved entries; collect non-surfaced ones for the override field.
// ------------------------------------------------------------------------
private _missing = [];
{
    private _task = _x;
    private _idx = _surfacedSet getOrDefault [_task, -1];
    if (_idx >= 0) then {
        _ctrl lbSetSelected [_idx, true];
    } else {
        _missing pushBackUnique _task;
    };
} forEach _selectedTasks;

// Suppress civic-only and insurgency entries from the override field
// when their dependencies aren't met. Without this strip, the
// filtered-from-listbox families would land here (since they're in
// _selectedTasks but not _surfacedSet) and the override text would
// list tasks that can't actually spawn. Save handler preserves them
// on the logic side so they re-appear in the listbox when conditions
// are met (civicState toggled ON / asymmetric OPCOM placed).
if (!_civicStateEnabled) then {
    _missing = _missing - _civicOnlyTasks;
};
if (!_hasAsymmetricOpcom) then {
    _missing = _missing - _insurgencyTasks;
};

private _editCtrl = _display controlsGroupCtrl 102;
if (!isNull _editCtrl) then {
    _editCtrl ctrlSetText (_missing joinString ",");
};

[
    "ALIVE TaskTypeChoice LOAD: kind=%1 varName=%2 sqm='%3' resolved='%4' registry=%5 listboxRows=%6 ticked=%7 missing=%8",
    _kindToken, _varName, _sqmValue, _value, _registryName, lbSize _ctrl, count _selectedTasks - count _missing, count _missing
] call ALiVE_fnc_dump;
