#include "\x\alive\addons\main\script_component.hpp"
SCRIPT(edenTaskTypeChoiceSave);
/* ----------------------------------------------------------------------------
Function: ALIVE_fnc_edenTaskTypeChoiceSave

Description:
Eden-attribute `attributeSave` handler for the ALiVE_TaskTypeChoice
family. Reads the multi-select listbox ticks (IDC 100) and the
override Edit text (IDC 102), merges into a deduped comma-separated
string, writes to both the attribute "value" slot and the consuming
module's logic variable.

Storage format on the logic / SQM:
    Task1,Task2,Task3
Flat comma-separated (no faction keying).

Parameters:
    [_display, _varName]
    _display    : DISPLAY - Eden attribute display
    _varName    : STRING - logic-variable name (e.g.
                  "customAutoGeneratedTasks")

Returns:
    STRING - the merged value (also persisted via setVariable + value slot)

Author:
Jman
---------------------------------------------------------------------------- */

private _display = controlNull;
private _varName = "customAutoGeneratedTasks";

if (typeName _this == "ARRAY") then {
    if (count _this > 0) then { _display = _this select 0; };
    if (count _this > 1 && {typeName (_this select 1) == "STRING"}) then { _varName = _this select 1; };
} else {
    _display = _this;
};

if (isNull _display) exitWith {
    diag_log "ALIVE TaskTypeChoice SAVE: null display";
    "";
};

private _merged = [];

// ------------------------------------------------------------------------
// Listbox ticks - lbData is the task name verbatim (no FACTION:: prefix
// in the flat-list variant).
// ------------------------------------------------------------------------
private _ctrl = _display controlsGroupCtrl 100;
if (!isNull _ctrl) then {
    {
        private _task = _ctrl lbData _x;
        if (_task != "") then { _merged pushBackUnique _task; };
    } forEach (lbSelection _ctrl);
};

// ------------------------------------------------------------------------
// Override field - bare comma-separated list, append to the merged set.
// ------------------------------------------------------------------------
private _editCtrl = _display controlsGroupCtrl 102;
private _overrideText = if (!isNull _editCtrl) then { ctrlText _editCtrl } else { "" };
if (_overrideText != "") then {
    {
        private _t = _x;
        while {count _t > 0 && {(_t select [0, 1]) == " "}} do { _t = _t select [1] };
        while {count _t > 0 && {(_t select [count _t - 1, 1]) == " "}} do { _t = _t select [0, count _t - 1] };
        if (_t != "") then { _merged pushBackUnique _t; };
    } forEach ([_overrideText, ","] call CBA_fnc_split);
};

// ------------------------------------------------------------------------
// Dependency-driven preservation: the load handler hides families
// whose dependencies aren't currently met (civic-only when
// civicState=OFF; insurgency tasks when no asymmetric OPCOM is
// placed). Without the preservation block below, saving in that
// state would WIPE any existing dependency-gated entries on the
// logic - the user would have to re-tick them after the dependency
// flips. Re-merge those entries from the existing saved value
// before serialising.
private _civicOnlyTasks = ["MedicalOutreach", "CheckpointPartnership", "InformantExfiltration", "MarketReopening"];
private _insurgencyTasks = ["InsurgencyDestroyAssets", "InsurgencyPatrol"];
private _selected = get3DENSelected "logic";
private _logicObj = if (count _selected > 0) then { _selected select 0 } else { objNull };

// Trim helper for entries pulled from the saved CSV.
private _trim = {
    params ["_t"];
    while {count _t > 0 && {(_t select [0, 1]) == " "}} do { _t = _t select [1] };
    while {count _t > 0 && {(_t select [count _t - 1, 1]) == " "}} do { _t = _t select [0, count _t - 1] };
    _t
};

if (!isNull _logicObj) then {
    private _csEnabledVar = _logicObj getVariable ["civicStateEnabled", false];
    private _csEnabled = switch (typeName _csEnabledVar) do {
        case "BOOL":   { _csEnabledVar };
        case "STRING": { (toLower _csEnabledVar) == "true" };
        default        { false };
    };

    // Detect asymmetric OPCOM presence (same idiom as load handler +
    // fnc_edenValidateOpcomFactions). all3DENEntities returns mixed
    // buckets; only Object-typed module entries matter.
    private _hasAsymmetricOpcom = false;
    {
        {
            if (_x isEqualType objNull && {!isNull _x} && {(typeOf _x) == "ALiVE_mil_OPCOM"}) then {
                private _ct = _x getVariable ["controltype", ""];
                if (typeName _ct == "STRING" && {(toLower _ct) == "asymmetric"}) exitWith {
                    _hasAsymmetricOpcom = true;
                };
            };
        } forEach _x;
        if (_hasAsymmetricOpcom) exitWith {};
    } forEach all3DENEntities;

    private _hiddenTasks = [];
    if (!_csEnabled) then { _hiddenTasks append _civicOnlyTasks; };
    if (!_hasAsymmetricOpcom) then { _hiddenTasks append _insurgencyTasks; };

    if (count _hiddenTasks > 0) then {
        private _existingValue = _logicObj getVariable [_varName, ""];
        if (typeName _existingValue == "STRING" && {_existingValue != ""}) then {
            {
                private _t = [_x] call _trim;
                if (_t != "" && {_t in _hiddenTasks}) then {
                    _merged pushBackUnique _t;
                };
            } forEach ([_existingValue, ","] call CBA_fnc_split);
        };
    };
};

// ------------------------------------------------------------------------
// Sort for deterministic serialisation across re-saves.
// ------------------------------------------------------------------------
_merged sort true;
private _value = _merged joinString ",";

_display setVariable ["value", _value];

if (!isNull _logicObj) then {
    _logicObj setVariable [_varName, _value];
};

diag_log format ["ALIVE TaskTypeChoice SAVE: varName=%1 value='%2'", _varName, _value];

_value
