#include "\x\alive\addons\main\script_component.hpp"
SCRIPT(edenTaskTypeChoiceLoad);
/* ----------------------------------------------------------------------------
Function: ALIVE_fnc_edenTaskTypeChoiceLoad

Description:
Eden-attribute `attributeLoad` handler for the ALiVE_TaskTypeChoice
family. Populates the multi-select listbox (IDC 100) with the
available task-type names for the registry the variant control points
at (e.g. ALIVE_autoGeneratedTasks for the _AutoGenerated variant),
ticks rows that match the saved value, and pre-fills the override
Edit (IDC 102) with anything saved that the listbox doesn't surface.

Storage format on the logic / SQM:
    Task1,Task2,Task3
Flat comma-separated string (no faction keying - tasks are global,
not per-faction). Empty value = no override (the resolver leaves the
target registry unchanged at runtime).

Flow:
1. Lazy-load Tasks.hpp if the target registry is nil (3DEN editor
   context where staticDataHandler hasn't run)
2. Resolve stored value (priority: SQM `_value` > logic var > "")
3. Parse stored value into a deduped list
4. Populate listbox from registry contents
5. Tick rows that match parsed entries
6. Anything in the parsed value not surfaced in the listbox goes
   into the override Edit (so unrecognised mod tasks are preserved)

Parameters:
    [_display, _kindToken, _varName, _titleStr, _sqmValue]
    _display    : DISPLAY - Eden attribute display
    _kindToken  : STRING - identifies the target registry
                  ("autoGenerated" -> ALIVE_autoGeneratedTasks)
    _varName    : STRING - logic-variable name (e.g.
                  "customAutoGeneratedTasks")
    _titleStr   : STRING - localised title text or $STR_ key
    _sqmValue   : STRING - SQM-deserialised value (Cfg3DEN's `_value`)

Author:
Jman
---------------------------------------------------------------------------- */

private _display = controlNull;
private _kindToken = "autoGenerated";
private _varName = "customAutoGeneratedTasks";
private _titleStr = "Override:";
private _sqmValue = "";

if (typeName _this == "ARRAY") then {
    if (count _this > 0) then { _display = _this select 0; };
    if (count _this > 1 && {typeName (_this select 1) == "STRING"}) then { _kindToken = _this select 1; };
    if (count _this > 2 && {typeName (_this select 2) == "STRING"}) then { _varName = _this select 2; };
    if (count _this > 3 && {typeName (_this select 3) == "STRING"}) then { _titleStr = _this select 3; };
    if (count _this > 4 && {typeName (_this select 4) == "STRING"}) then { _sqmValue = _this select 4; };
} else {
    _display = _this;
};

if (isNull _display) exitWith {
    diag_log "ALIVE TaskTypeChoice LOAD: null display";
};

// ------------------------------------------------------------------------
// Title text. Resolves $STR_ keys via localize.
// ------------------------------------------------------------------------
private _titleResolved = _titleStr;
if (count _titleStr > 0 && {(_titleStr select [0, 1]) == "$"}) then {
    _titleResolved = localize (_titleStr select [1]);
};
private _titleCtrl = _display controlsGroupCtrl 101;
if (!isNull _titleCtrl) then { _titleCtrl ctrlSetText _titleResolved; };

// ------------------------------------------------------------------------
// Map kind token to global registry variable name.
// ------------------------------------------------------------------------
private _registryName = switch (_kindToken) do {
    case "autoGenerated": { "ALIVE_autoGeneratedTasks" };
    default               { "" };
};

// ------------------------------------------------------------------------
// Lazy-load Tasks.hpp if the target registry is nil. Same trick as
// fnc_listFactionVehicleClasses uses for the static-data registries -
// 3DEN editor context doesn't run staticDataHandler, so the global is
// undefined until we force-compile the .hpp here. Aliases the ALiVE
// hash wrappers (Tasks.hpp uses createHashMap-style flat assignments,
// no hash calls, so technically not needed, but defensive).
// ------------------------------------------------------------------------
if (_registryName != "" && {isNil _registryName}) then {
    diag_log format ["ALIVE TaskTypeChoice LOAD: registry %1 not loaded - lazy-loading Tasks.hpp", _registryName];
    if (isNil "ALIVE_fnc_hashCreate") then { ALIVE_fnc_hashCreate = CBA_fnc_hashCreate; };
    if (isNil "ALIVE_fnc_hashSet")    then { ALIVE_fnc_hashSet    = CBA_fnc_hashSet; };
    if (isNil "ALIVE_fnc_hashGet")    then { ALIVE_fnc_hashGet    = CBA_fnc_hashGet; };
    call compile preprocessFileLineNumbers "\x\alive\addons\main\static\Tasks.hpp";
};

private _registryClasses = if (_registryName != "") then { missionNamespace getVariable [_registryName, []] } else { [] };
if (typeName _registryClasses != "ARRAY") then { _registryClasses = []; };

// ------------------------------------------------------------------------
// Stored-value resolution.
// ------------------------------------------------------------------------
private _selected = get3DENSelected "logic";
private _logicObj = if (count _selected > 0) then { _selected select 0 } else { objNull };

private _storedFromLogic = if (!isNull _logicObj) then {
    _logicObj getVariable [_varName, nil]
} else {
    nil
};
private _edenValue = _display getVariable "value";

private _value = "";
if (!isNil "_edenValue" && {typeName _edenValue == "STRING"} && {_edenValue != ""}) then {
    _value = _edenValue;
};
if (!isNil "_storedFromLogic" && {typeName _storedFromLogic == "STRING"} && {_storedFromLogic != ""}) then {
    _value = _storedFromLogic;
};
if (_sqmValue != "") then {
    _value = _sqmValue;
};

// ------------------------------------------------------------------------
// Parse stored value into deduped list.
// ------------------------------------------------------------------------
private _selectedTasks = [];
if (_value != "") then {
    {
        private _t = _x;
        while {count _t > 0 && {(_t select [0, 1]) == " "}} do { _t = _t select [1] };
        while {count _t > 0 && {(_t select [count _t - 1, 1]) == " "}} do { _t = _t select [0, count _t - 1] };
        if (_t != "") then { _selectedTasks pushBackUnique _t };
    } forEach ([_value, ","] call CBA_fnc_split);
};

// ------------------------------------------------------------------------
// Populate listbox from the registry. Sort alphabetically so the order
// is stable across re-opens regardless of how Tasks.hpp orders entries.
// ------------------------------------------------------------------------
private _ctrl = _display controlsGroupCtrl 100;
if (isNull _ctrl) exitWith {
    diag_log "ALIVE TaskTypeChoice LOAD: listbox control (IDC 100) not found";
};
lbClear _ctrl;

private _surfacedSet = createHashMap;
private _sortedRegistry = +_registryClasses;
_sortedRegistry sort true;
{
    private _task = _x;
    if (typeName _task == "STRING" && {_task != ""}) then {
        private _idx = _ctrl lbAdd _task;
        _ctrl lbSetData [_idx, _task];
        _surfacedSet set [_task, _idx];
    };
} forEach _sortedRegistry;

// ------------------------------------------------------------------------
// Tick saved entries; collect non-surfaced ones for the override field.
// ------------------------------------------------------------------------
private _missing = [];
{
    private _task = _x;
    private _idx = _surfacedSet getOrDefault [_task, -1];
    if (_idx >= 0) then {
        _ctrl lbSetSelected [_idx, true];
    } else {
        _missing pushBackUnique _task;
    };
} forEach _selectedTasks;

private _editCtrl = _display controlsGroupCtrl 102;
if (!isNull _editCtrl) then {
    _editCtrl ctrlSetText (_missing joinString ",");
};

diag_log format [
    "ALIVE TaskTypeChoice LOAD: kind=%1 varName=%2 sqm='%3' resolved='%4' registry=%5 listboxRows=%6 ticked=%7 missing=%8",
    _kindToken, _varName, _sqmValue, _value, _registryName, lbSize _ctrl, count _selectedTasks - count _missing, count _missing
];
